# Generated by Django 5.2.3 on 2025-07-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='flight_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
