# Generated by Django 5.2.3 on 2025-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flights_flight_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage_objects',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('back_ground_for_flights', models.ImageField(upload_to='obj/')),
            ],
        ),
    ]
